Please review my PR and suggest the required changes
marsiitr/Drone-Simulation pull request #1
Opened 2022-07-24 17:56 UTC by abyasingh

2022-07-25 22:01 UTC, Nageshbansal reviewed
images should be in ```images and videos/images``` directory.

2022-07-25 22:02 UTC, Nageshbansal reviewed
directories names should be according to guidlines

2022-07-25 22:08 UTC, Nageshbansal commented on README.md
> +![Final Product](https://github.com/abyasingh/Drone-Simulation/blob/main/Images%20and%20Videos/Simultion%20of%20drone.png)
images should be enclosed in ```<p></p>```  tags, so that they can be aligned in the center i.e ```align="center```

2022-07-25 22:08 UTC, Nageshbansal commented on README.md
> +![Takeoff_P1](https://github.com/abyasingh/Drone-Simulation/blob/main/Images%20and%20Videos/Take-off%20Scrpit%20P1.png)
instead of adding screenshots of code, you can use code-blocks

2022-07-25 22:08 UTC, Nageshbansal commented on README.md
> +2. Harshini S.
add links to GitHub profiles for all of the mentors

2022-07-25 22:08 UTC, Nageshbansal commented on README.md
> +
you can add installation steps for package

2022-07-25 22:08 UTC, Nageshbansal commented on src/Take-off script.py
> +        print('waiting for service')
add comments in code for each of the method/functions and classes

2022-07-29 08:47 UTC, Nageshbansal commented on README.md
> +![Takeoff_P1](https://github.com/abyasingh/Drone-Simulation/blob/main/Images%20and%20Videos/Take-off%20Scrpit%20P1.png)
By code-blocks I meant, adding a snippet of the code in the markdown/Readme file. for e.g. 
```
def test():
   return None
```

2022-07-30 05:44 UTC, abyasingh commented
Sir I've made the changes, please review.

2022-08-01 19:59 UTC, Nageshbansal reviewed
change the filename of video

2022-08-01 20:03 UTC, Nageshbansal commented on README.md
> +![Final Product](https://github.com/abyasingh/Drone-Simulation/blob/main/Images%20and%20Videos/Images/Simultion%20of%20drone.png)
images should be enclosed in the ``` <p>``` tags, so that they can be aligned in the center

2022-08-01 20:03 UTC, Nageshbansal commented on README.md
> +![Takeoff_P1](https://github.com/abyasingh/Drone-Simulation/blob/main/Images%20and%20Videos/Images/Take-off%20Scrpit%20P1.png)
instead of adding screenshots of the code, you can add snippets or just add the URL to the script.

2022-08-03 07:44 UTC, abyasingh commented
Sir I have done all the changes recommended by you.

2022-08-07 18:42 UTC, Nageshbansal reviewed
1. remove the screenshots of the code from the ```images and videos``` directory
2. add report in the ``` Poster and Report``` directory
3.  Instead of adding link to the script, you can add a snippet of the code in your markdown, you can follow this tutorial for your reference https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

2022-08-07 20:54 UTC, abyasingh commented
Yes Sir, I've done all the changes. Please review.

2022-08-07 21:06 UTC, Nageshbansal reviewed
report should be in ```.pdf``` format

2022-08-08 12:59 UTC, abyasingh commented
Sir I've converted the report in pdf form.

2022-08-14 19:57 UTC, Nageshbansal commented
Are you done with all of the mentioned changes?

2022-08-15 18:16 UTC, abyasingh commented
Yes Sir

2022-08-19 12:59 UTC, SanjeevKrishnan commented
> Yes Sir

@Nageshbansal Follow this up and tag me once the repo is ready for merge.

2022-08-25 17:56 UTC, Nageshbansal requested changes

2022-08-25 17:56 UTC, Nageshbansal commented on README.md
> +> roslaunch mavros px4.launch fcu_url:="udp://:14540@127.0.0.1:14557"
Instead of using Blockquotes ( `>') , use code-blocks (```) for adding commands in README.md

2022-08-25 17:56 UTC, Nageshbansal commented on README.md
> +2. [Harshini S.](https://github.com/Harshini-festus)
Mentors' Names should be in alphabetical order.

2022-08-25 17:56 UTC, Nageshbansal commented on README.md
> +1. [For installation of noetic version of Ubuntu](http://wiki.ros.org/noetic/Installation/Ubuntu)
Remove `For` from the References and Justify the content of the README.

2022-08-26 03:27 UTC, abyasingh commented
SIr, I've done the changes

2022-08-26 12:42 UTC, Nageshbansal approved these changes
LGTM, Good work.
@SanjeevKrishnan I think we're done with changes, let me know if we can merge this PR.

2026-05-24 13:08 UTC, merged